### ISSUE TITLE
[예약관리] 일반 회원은 예약 취소를 할 수 있습니다.

### ISSUE THREAD

**Issue by jeongeun1** [ssg-java3-240304/my-seat-dang#37]
# 🌈 Success criteria
1. 일반 회원은 예약을 취소할 수 있습니다.

# 👷To-do
- [x] 일반 회원은 예약을 취소할 수 있습니다.

# 👓 Review

**Comment by CstoneKu** [comment]
https://github.com/ssg-java3-240304/my-seat-dang/pull/326
